### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by absolutelyNoWarranty** [turi-code/SFrame#376]
I am trying to build with msys SFrame for Python3.4 on Windows. The `configure` step seemed to work fine but `make` is failing saying that it can't find `libxml/xmlversion.h` (but it's right there in the `deps` folder)

```
In file included from C:/WinPython-64bit-3.4.4.3Qt5/git_repos/SFrame/oss_src/fileio/oss_webstor/wsconn.cpp:30:0:
C:/WinPython-64bit-3.4.4.3Qt5/git_repos/SFrame/deps/local/include/libxml2/libxml/parser.h:15:31: fatal error: libxml/xmlversion.h: No such file or directory
compilation terminated.
oss_src/fileio/CMakeFiles/fileio.dir/build.make:113: recipe for target 'oss_src/fileio/CMakeFiles/fileio.dir/oss_webstor/wsconn.cpp.obj' failed
make[2]: *** [oss_src/fileio/CMakeFiles/fileio.dir/oss_webstor/wsconn.cpp.obj] Error 1
CMakeFiles/Makefile2:475: recipe for target 'oss_src/fileio/CMakeFiles/fileio.dir/all' failed
make[1]: *** [oss_src/fileio/CMakeFiles/fileio.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

```
